name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: sudo apt-get update && sudo apt-get install -y musl-tools build-essential make linux-libc-dev && touch artifacts/bootstrap-rootfs.ext4
    - name: Add rustup target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: make build
    - name: Run tests
      run: make test
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fs-writer
        path: |
          target/x86_64-unknown-linux-musl/release/fs-writer
